# ESPHome based doorbell
# https://www.zuidwijk.com/product/smart-doorbell/
# https://github.com/zuidwijk/esphome-doorbell

substitutions:
  name: doorbell
  friendly_name: Doorbell

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platform: ESP8266
  board: d1_mini
  project:
    name: zuidwijk.doorbell
    version: "2.0"
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key01

# Enable over-the-air updates.
ota:
  platform: esphome
  password: !secret ota_password01

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

# Connect to WiFi.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_hotspot_password

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
 
# Text sensors with general information.
text_sensor:
  - platform: version
    name: Doorbell ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Doorbell IP
    ssid:
      name: Doorbell SSID
    bssid:
      name: Doorbell BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Doorbell Uptime
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Doorbell WiFi Signal
    update_interval: 60s

# Global to store the on/off state of the chime 
globals:
  - id: chime
    type: bool
    restore_value: true
    initial_value: 'true'
 
# Exposed switches.
switch:
  - platform: restart
    name: Doorbell Restart
  # Switch to turn on/off the chime.
  - platform: gpio
    pin:
      number: D1
      inverted: false
    name: Doorbell Relay
    id: relay
    internal: true
    icon: mdi:alarm-bell

  - platform: template
    name: Doorbell Chime Active
    id: chime_active
    restore_mode: 'RESTORE_DEFAULT_OFF'
    turn_on_action:
      - globals.set:
          id: chime
          value: 'true'
    turn_off_action:
      - globals.set:
          id: chime
          value: 'false'
    lambda: |-
      return id(chime);

# Binary sensor representing the
# Doorbell button push.     
binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    name: Doorbell
    filters:
      # Small filter, to debounce the button press.
      - delayed_on: 25ms
      - delayed_off: 25ms
    on_press:
      # Only turn on the chime when it is active.
      then:
        if:
          condition:
            - switch.is_on: chime_active
          then:
            - switch.turn_on: relay
    on_release:
      # On release, turn of the chime.
      - switch.turn_off: relay        
 
  - platform: status
    name: Status Doorbell
