alias: Notify Doorbell
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell
    from: "off"
    to: "on"
condition: []
action:
  - service: notify.all_devices
    data:
      message: Ding dong! Someone is at the door!
      title: Doorbell pressed.
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
