alias: Notify Doorbell
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.doorbell_doorbell
    from: "off"
    to: "on"
conditions: []
actions:
  - action: notify.all_mobile_devices
    data:
      message: Ding dong! Someone is at the door!!
      title: Doorbell Pressed.
      data:
        push:
          category: doorbell
          interruption-level: critical
        channel: alarm
